name: CI

on:
  pull_request:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  check:
    name: 'Build & test'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare cache key
      run: |
        cp Cargo.lock cache-fingerprint
        echo $RUSTFLAGS >> cache-fingerprint
        echo $(rustc -V) >> cache-fingerprint
    - name: Restore cargo cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('cache-fingerprint') }}
        restore-keys: ${{ runner.os }}-cargo
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
